### ISSUE TITLE
Регистрация ника с пробелами

### ISSUE THREAD

**Issue by LaineZ** [hadron-powered/si-site#15]
Уберите возможность регистрировать ники с пробелами

**Comment by Fingercomp** [comment]
А она есть?

**Comment by LaineZ** [comment]
Да

**Comment by Fingercomp** [comment]
А можно ли узнать способ подтверждения этого, когда сайт оффлайн?..

**Comment by LaineZ** [comment]
Ну ты его включи и проверь...

**Comment by LaineZ** [comment]
https://i.imgur.com/jIDmHFa.png
вот пруф

**Comment by Fingercomp** [comment]
Гм. Добавил якоря. Теперь не должно нифига матчиться.
